### ISSUE TITLE
Unable to set multiple values on load

### ISSUE THREAD

**Issue by pranavsreedhar92** [basvandenberg/ng-select#131] opened 2017-02-27 06:51 UTC
Not able to bind selected values to multiselect.

**HTML Page**
```
<ng-select
       id="supervisors"
       [options]="clientsOptions"
       [multiple]="clientsMultiple"
       placeholder="Select Client"
       formControlName="client"
       [allowClear]="true" [(ngModel)]="clientsSelected">
</ng-select>
```
**TS Page**
```
    clientsMultiple       : boolean = true;
    clientsOptions        : Array<any> = [];
    clientsSelected       : Array<any> = [];

    let opts = [];
    for (let i = 0; i < this.client.length; i++) {
	opts[i] = {
		value: data[i].profileId.toString(),
		label: data[i].name.toString()
	};
    }
    this.clientOptions = opts.slice(0);
```
**Selected format is** 
Array [ "32d8d76a-8b4", "ef2cc2df-e4e" ]

Able to show the complete list but selected values are not getting selected.

**Comment by basvandenberg** [comment] 2017-02-27 10:21
Can you reproduce this with a plunkr?

**Comment by basvandenberg** [comment] 2017-05-26 20:15
From your example code I can't figure out what the issue is, therefore I'll close this issue for now. Please let me know if you still think this is a bug.

**Closed by basvandenberg** 2017-05-26 20:15 UTC
