### ISSUE TITLE
Error beta.1

### ISSUE THREAD

**Issue by juliosogiteck** [basvandenberg/ng-select#65] opened 2017-01-09 09:39 UTC
Error to init application: 
Uncaught TypeError: ctorParameters.map is not a function

In version alpha is works!

Windows 10
npm 3.10.3
Angular 2

**Comment by matthewhegarty** [comment] 2017-01-10 20:16
Try [upgrading](https://github.com/angular/angular-cli#updating-angular-cli) to latest version of angular-cli

**Comment by basvandenberg** [comment] 2017-01-15 20:00
Did you manage to resolve this issue @juliosogiteck? Would be nice to close this issue if it has been resolved. There haven't been any other similar issues reporter and I couldn't reproduce the issue.

**Comment by DeyuanTan** [comment] 2017-01-16 07:46
same problem： TypeError: ctorParameters.map is not a function

**Comment by basvandenberg** [comment] 2017-01-17 19:17
Bumped into this [stackoverflow question](http://stackoverflow.com/questions/41285889/ctorparameters-map-is-not-a-function-in-angular2-mdl/41444599#41444599) today. 

> How to solve this Problem?:
>
> 1. You can update your angular versions (or packages that are trying to compile your angular2 code) to the new compiler output format. E.g. at least @angular/*@2.3.1. (If you are using angular-cli you should upgrade your project to angular-cli@1.0.0-beta.24)

**Comment by waveywhite** [comment] 2017-01-24 14:25
For those that don't use angular-cli I solved this problem by upgrading to the the latest version of angular quickstart

See [latest version of package.json](https://github.com/angular/quickstart/blob/master/package.json)

**Closed** 2017-06-03 08:58 UTC
