### ISSUE TITLE
AoT is not working

### ISSUE THREAD

**Issue by shprink** [basvandenberg/ng-select#113] opened 2017-02-18 17:52 UTC
```
[16:53:04]  ngc started ... 
can't resolve module ./select.component from /var/lib/jenkins/jobs/Cadulis-App-INTEG2-Deploy/workspace/src/node_modules/angular2-select/dist/angular2-select.d.ts
[16:53:06]  build prod failed: Cannot read property 'SelectComponent' of undefined, resolving symbol SelectModule in 
            /var/lib/jenkins/jobs/Cadulis-App-INTEG2-Deploy/workspace/src/node_modules/angular2-select/dist/angular2-select.d.ts,
            resolving symbol SelectModule in 
            /var/lib/jenkins/jobs/Cadulis-App-INTEG2-Deploy/workspace/src/node_modules/angular2-select/dist/angular2-select.d.ts
```

**Comment by basvandenberg** [comment] 2017-02-24 21:42
Difficult to tell what the issue is here. What version are you using? Could you show some of the code? For example your `app.module.ts` file?

**Comment by shprink** [comment] 2017-02-26 11:26
Use Angular CLI, add your lib and build AoT to reproduce.

**Comment by usego** [comment] 2017-03-07 13:50
I'm dreaming to integrate your component to our app, but AOT support is a showstopper there. Rollup fails with:

Error: 'SelectModule' is not exported by node_modules\angular2-select\index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
temp\aot\build\js\angular2App\app\app.module.js (35:9)

35: import { SelectModule } from 'angular2-select';
             ^

**Comment by basvandenberg** [comment] 2017-03-12 20:41
This issue should be resolved in the 1.0.0-beta.4 release. Please let me know if this is not the case, then I'll reopen the issue.

**Closed by basvandenberg** 2017-03-12 20:41 UTC

**Comment by usego** [comment] 2017-04-29 08:06
I've updated to beta.5 from beta.3. There is still an issue with treeshaking, seems to be SelectComponent related. I have to change to the following to fix aot build:

components:

instead of 
import { SelectComponent } from 'ng-select';

do
import { SelectComponent } from 'ng-select/dist/select.component.js';

Otherwise I'm getting

![image](https://cloud.githubusercontent.com/assets/1269995/25553978/8cf69336-2cca-11e7-8df3-ab707c2a658c.png)
