### ISSUE TITLE
Initial value not displayed when container has OnPush change detection strategy

### ISSUE THREAD

**Issue by mrkosima** [basvandenberg/ng-select#107] opened 2017-02-11 20:47 UTC
When container has OnPush detection strategy, initial value not displayed at ng-select control.
After click or next change detection value will be displayed.
Found at `alpha-12`
Actual for `beta.3`

https://plnkr.co/edit/Afx2NL?p=preview

**Comment by albohlabs** [comment] 2017-11-22 12:08
Got the same issue with angular `5.0.2` and ng-select `1.0.0-rc.3`.
Is there a reason why #112 is not merged?

**Comment by meiuqer** [comment] 2018-07-27 11:15
How does this commit fix this issue? Having the same problem atm.

**Comment by benelliott** [comment] 2018-07-27 11:16
The PR has not been merged.

**Comment by meiuqer** [comment] 2018-07-27 11:19
I know, i'm trying to implement it for my project. But it's not working.

I also don't really see how this can fix the issue? Does [style.width] force change detection where [ngStyle] doesnt?

**Comment by meiuqer** [comment] 2018-07-27 11:59
Hmm, i really dont think this commit is a fix. Beside the merge issues i really can't see how this would solve the onPush issue. 

I'm trying to figure out how to do it myself but to no avail. If a contributor would be so kind to look at this, that would be awesome!

**Comment by benelliott** [comment] 2018-07-27 12:02
I believe I fixed this by changing 

```typescript
    private updateState() {
        this.placeholderView = this.optionList.hasSelected ? '' : this.placeholder;
        setTimeout(() => {
            this.updateFilterWidth();
        });
    }
```

to 

```
    private updateState() {
        this.placeholderView = this.optionList.hasSelected ? '' : this.placeholder;
        setTimeout(() => {
            this.updateFilterWidth();
            this.changeDetectorRef.markForCheck();
        });
    }
```

but can't confirm right now.

**Comment by meiuqer** [comment] 2018-07-27 12:06
Hmm i tried it but i doesn't work. Although this is a very good idea, i do think that the changeDetectorRef needs to be initialized somewhere? Is it even possible to use it like this in an external library?

**Comment by benelliott** [comment] 2018-07-27 12:31
Yeah you need to inject ChangeDetectorRef in the constructor:

```
 constructor(
        private hostElement: ElementRef,
        private changeDetectorRef: ChangeDetectorRef
    ) {}
```

**Comment by benelliott** [comment] 2018-07-27 12:31
This would be a modification to the library itself, not to your code.

**Comment by meiuqer** [comment] 2018-07-27 12:41
Thanks for the help! At first glance this seems to work. I'm working directly in the compiled es5.js so it was a little bit of searching.

**Comment by meiuqer** [comment] 2018-07-30 07:38
@benelliott maybe you should make a PR for this? cause i think this is a good solution for the problem!

**Comment by benelliott** [comment] 2018-07-30 09:06
@meiuqer Sure, I'll take a look.

**Comment by sebastientromp** [comment] 2018-08-09 14:56
Would love support for OnPush on the parent component as well

**Comment by sebastientromp** [comment] 2018-08-09 15:55
The proposed fix didn't work for me, I'll start digging deeper into that

**Comment by meiuqer** [comment] 2018-08-09 15:58
Could you provide some info as to why its not working? Got any errors you could share? Thanks

**Comment by sebastientromp** [comment] 2018-08-09 18:48
Yeah sorry, that was a bit short from me :)
Actually nothing happened, as if change detection was not happening. Changing the `markForCheck` to `detectChanges` did the trick though.
I don't have a minimal project to reproduce unfortunately.

**Comment by meiuqer** [comment] 2018-08-09 19:53
that's kinda wierd though. markForCheck() is for onPush(). but if it works it works i guess :)

**Comment by meiuqer** [comment] 2018-08-10 07:12
@sebastientromp could you show me where you altered the code and what code you added? I also still have trouble getting it to work correctly. Maybe with your insights i could solve my problem.

**Comment by sebastientromp** [comment] 2018-08-10 08:30
Sure, I just did this:
```
    private updateState() {
        this.placeholderView = this.optionList.hasSelected ? '' : this.placeholder;
        setTimeout(() => {
            this.updateFilterWidth();
            this.changeDetectorRef.detectChanges();
        });
    }
```
(so simply replaced your `markForCheck()` with `detectChanges()`. I'm still just discovering the OnPush change detection strategy and fumbling around, so I don't really know what I'm doing :)

**Comment by meiuqer** [comment] 2018-08-10 08:36
Thanks for the response. Could you do one test for me? Of maybe you already did it. Can you test this with 'ng build --aot'? Because i do exactly the same and it works with 'ng serve' and not with 'ng build --aot' and i cant, for the life of me, figure out why this can happen.

**Closed** 2020-07-13 20:07 UTC
