### ISSUE TITLE
Unpredictable error while using select

### ISSUE THREAD

**Issue by psg2** [basvandenberg/ng-select#162] opened 2017-04-24 05:38 UTC
While I'm testing the app, sometimes this error occurs, and when it does, I need to refresh the page for the select to work properly. So I don't quite know what is the cause of the error, or even if it's related to this package, might be something in my particular project.

![image](https://cloud.githubusercontent.com/assets/14082115/25323508/11b71f34-2896-11e7-9e22-9bf0bc81530d.png)

The contents of my package.json:
"@angular/animations": "^4.0.3",
    "@angular/cli": "1.0.0",
    "@angular/common": "^4.0.3",
    "@angular/compiler": "^4.0.3",
    "@angular/compiler-cli": "^4.0.3",
    "@angular/core": "^4.0.3",
    "@angular/forms": "^4.0.3",
    "@angular/http": "^4.0.3",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "^4.0.3",
    "@angular/platform-browser-dynamic": "^4.0.3",
    "@angular/router": "^4.0.3",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.22",
    "@swimlane/ngx-datatable": "^7.1.1",
    "@types/leaflet": "^1.0.58",
    "angular-calendar": "^0.11.0",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "express": "^4.15.2",
    "firebase": "^3.7.4",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "leaflet": "^1.0.3",
    "ng-pick-datetime": "^4.0.1",
    "ng-select": "^1.0.0-beta.5",
    "rxjs": "^5.1.0",
    "zone.js": "0.8.5"

I could not reproduce the error on a smaller project yet.

Has anyone else faced this problem before or something similar?

**Comment by basvandenberg** [comment] 2017-04-29 08:03
That might be a bug indeed, I'll have a look at it. Thank for reporting.

**Comment by basvandenberg** [comment] 2017-04-29 08:14
I am not able to reproduce this error. Based on the error I assume you use single select? Could you please post the <ng-select> template you use? That would help me find this bug. Thanks!

**Comment by psg2** [comment] 2017-04-29 17:13
Gists for the html template and the component.
https://gist.github.com/psg2/6742a3e9752f964bfc1da7b7e0e49ebf
https://gist.github.com/psg2/fd69e9754dcdc1a84d2b2228b1788c55

**Comment by basvandenberg** [comment] 2017-04-29 19:38
Hi @psg2, thanks for the gists.

An interesting bug this... From the error message I understand what happened (tried to clear the filter input in the dropdown, but the dropdown is not there anymore). But I don't understand how this could have happened, clearing the filter happens before the drop down is closed.

Anyways, I now realize that clearing the filter input in the dropdown is not needed, so I'll remove this function call. This should prevent this error.

**Comment by psg2** [comment] 2017-04-29 22:08
I've tried what you did in your commit here.
The error message has certainly disappeared, but the error persists, both select tags do not open until I do a page refresh.
It may be something in my specific project not loading correctly.

**Comment by basvandenberg** [comment] 2017-06-03 10:55
Might be something specific to your project indeed, will close this issue for now. If you still find out that this is a ng-select bug, then please let me know so that I can reopen this issue.

**Closed by basvandenberg** 2017-06-03 10:55 UTC
