### ISSUE TITLE
Placeholder - ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked.

### ISSUE THREAD

**Issue by Tolitech** [basvandenberg/ng-select#208] opened 2017-07-13 17:46 UTC
In this beta.6, I have the following bug:

It does not work:

`<ng-select [(ngModel)]="id" [options]="items" [placeholder]="'shared.input.select' | translate" [notFoundMsg]="'shared.input.selectNotFound' | translate" [multiple]="true"></ng-select>`

Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. 
in SelectComponent.ngfactory.js:135:27

If I remove the placeholder, it starts working.

`<ng-select [(ngModel)]="id" [options]="items" [notFoundMsg]="'shared.input.selectNotFound' | translate" [multiple]="true"></ng-select>`

**Comment by PMJMendes** [comment] 2017-07-21 09:58
This bug existed before, was fixed in beta 5 and was reintroduced in beta 6. The problem is the call to updateState in ngAfterViewInit. See my comment to [issue 143](https://github.com/basvandenberg/ng-select/issues/143).

**Comment by gieboyz** [comment] 2017-08-09 06:51
any update for this bugs??

**Comment by aniruddhadas9** [comment] 2017-08-11 16:50
I am facing the same issue in `beta.6`


```
SelectComponent.html:53 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '1'. Current value: '101'.
    at viewDebugError (core.es5.js:8420)
    at expressionChangedAfterItHasBeenCheckedError (core.es5.js:8398)
    at checkBindingNoChanges (core.es5.js:8562)
    at checkNoChangesNodeInline (core.es5.js:12423)
    at checkNoChangesNode (core.es5.js:12397)
    at debugCheckNoChangesNode (core.es5.js:13174)
    at debugCheckDirectivesFn (core.es5.js:13076)
    at Object.View_SelectComponent_13._co [as updateDirectives] (SelectComponent.html:59)
    at Object.debugUpdateDirectives [as updateDirectives] (core.es5.js:13058)
    at checkNoChangesView (core.es5.js:12217)
View_SelectComponent_13 @ SelectComponent.html:53
webpackJsonp.../../../core/@angular/core.es5.js.DebugContext_.logError @ core.es5.js:13398
webpackJsonp.../../../core/@angular/core.es5.js.ErrorHandler.handleError @ core.es5.js:1080
(anonymous) @ core.es5.js:4814
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.bundle.js:10782
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ polyfills.bundle.js:10532
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.runOutsideAngular @ core.es5.js:3844
webpackJsonp.../../../core/@angular/core.es5.js.ApplicationRef_.tick @ core.es5.js:4814
(anonymous) @ core.es5.js:4684
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.bundle.js:10782
onInvoke @ core.es5.js:3890
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invoke @ polyfills.bundle.js:10781
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.run @ polyfills.bundle.js:10532
webpackJsonp.../../../core/@angular/core.es5.js.NgZone.run @ core.es5.js:3821
next @ core.es5.js:4684
schedulerFn @ core.es5.js:3635
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:238
webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next @ Subscriber.js:185
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next @ Subscriber.js:125
webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber.next @ Subscriber.js:89
webpackJsonp.../../../../rxjs/Subject.js.Subject.next @ Subject.js:55
webpackJsonp.../../../core/@angular/core.es5.js.EventEmitter.emit @ core.es5.js:3621
checkStable @ core.es5.js:3855
onLeave @ core.es5.js:3934
onInvokeTask @ core.es5.js:3884
webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask @ polyfills.bundle.js:10814
webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask @ polyfills.bundle.js:10582
ZoneTask.invoke @ polyfills.bundle.js:10877
SelectComponent.html:53 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 2, nodeDef: {…}, elDef: {…}, elView: {…}}
```

**Comment by Eernie** [comment] 2017-09-20 07:19
@basvandenberg Any updates on this? We were on beta.5  but because of #192 we had to update. After updating to .6 we get this error. Resulting in a select that can't handle a placeholder in any way.

**Comment by basvandenberg** [comment] 2017-09-20 19:45
Just to be sure, this error only occurs for a development build, right? Not for a production build. That's what I observe at least.

In that case I fixed this by wrapping the statement that caused the error in a setTimeout. I'll try to release the new version soon, but this can take a week or two.

**Comment by gigioSouza** [comment] 2017-10-03 18:21
I'm facing that issue and I found out that this `ExpressionChangedAfterItHasBeenCheckedError` only occurs when using `multiple` configuration.

**Comment by benelliott** [comment] 2017-10-10 08:55
@basvandenberg Changed-after-checked errors will only ever occur on dev mode because they are found by running change detection twice. This happens as a precautionary measure in dev mode to find expressions whose values might be being changed by the CD itself but the change detection will not be re-run on prod so you won't see the error there.

**Comment by jessycormier** [comment] 2017-10-18 18:52
@basvandenberg The development build shows a true error, the error is hidden in production build. please see this comment on the angular repo: https://github.com/angular/angular/issues/6005#issuecomment-165905348

**Comment by raysuelzer** [comment] 2017-10-20 01:08
@benelliott  I agree with @jessycormier  here.  The error is shown in dev because it indicates that there is inconsistent state, which can cause problems in the real world.

**Comment by benelliott** [comment] 2017-10-20 08:59
@raysuelzer Yep, I'm not disagreeing that it's an error, I'm just explaining why it is only visible on dev.

**Closed** 2017-11-02 09:55 UTC
Labels: bug
